version: '3'

volumes:
  nginx-conf:
  nginx-vhost:
  nginx-html:
  nginx-certs:
  nginx-htpasswd:
  ghost-content:

networks:
  proxy:

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginx
    restart: always
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    security_opt:
      - label:type:docker_t
    volumes:
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro,z
      - nginx-conf:/etc/nginx/conf.d
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-certs:/etc/nginx/certs:ro
      - nginx-htpasswd:/etc/nginx/htpasswd:ro

  docker-gen:
    container_name: docker-gen
    image: jwilder/docker-gen
    restart: always
    networks:
      - proxy
    security_opt:
      - label:type:docker_t
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro,z
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro,z
      - nginx-conf:/etc/nginx/conf.d
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-certs:/etc/nginx/certs:ro
      - nginx-htpasswd:/etc/nginx/htpasswd:ro
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  ghost:
    container_name: ghost
    image: ghost:2.13.1
    restart: always
    networks:
      - proxy
    security_opt:
      - label:type:docker_t
    volumes:
      - ghost-content:/var/lib/ghost/content
    environment:

      # VIRTUAL_HOST: www.yuxikou.com
      # LETSENCRYPT_HOST: yuxikou.com
      # LETSENCRYPT_EMAIL: yuxikou@outlook.com
      # url: https://www.yuxikou.com
      # admin_url: https://www.yuxikou.com/admin

      VIRTUAL_HOST: www.kouriming.com
      LETSENCRYPT_HOST: www.kouriming.com
      LETSENCRYPT_EMAIL: yuxikou@outlook.com
      url: https://www.kouriming.com
      admin_url: https://www.kouriming.com/admin
      # database__client: mysql
      # database__connection__host: ghost-db
      # database__connection__user: root
      # database__connection__password: 364c9f07ce864bbcb8aaf09cacd25deb
      # database__connection__database: ghost
